### ISSUE TITLE
The Release Manager

### ISSUE THREAD

**Issue by Ragdata** [Ragdata/release-manager#11]
The Release Manager:

- [x] Libraries & Logging #12
  - [x] support for bash bits
  - [x] alternate library files
- [ ] The Changelog Builder #13
  - [x] config & templates
  - [ ] git log parser
  - [ ] changelog writer
- [ ] The Versioning Engine #14
  - [ ] versioner
  - [ ] bumper
- [ ] The Release Engine #15
  - [ ] git processor
  - [ ] packager
